[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flash-ml-query-reformulation"
version = "0.1.0"
dependencies = [
    "gradio==5.5.0",
    "requests==2.32.3",
]