services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "3000"]
    volumes:
      - ./backend:/app
    expose:
      - "3000"
    environment:
      - MODEL_PATH=SteveTran/T5-small-query-expansion-Q4
    deploy:
      replicas: 1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "8000:7860"
    environment:
      - ML_ENDPOINT_URL=http://backend:3000/rewrite
    depends_on:
      - backend

volumes:
  db_data:
