services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8040"]
    volumes:
      - ./backend:/app
    expose:
      - "8040"
    environment:
      - MODEL_PATH=SteveTran/T5-small-query-expansion-INT8
    
    deploy:
      replicas: 2
  nginx:
    image: nginx:latest
    ports:
      - "8040:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

volumes:
  db_data:
